#- setup variable for cluster installation
#- kubernetes dir
kube_config_dir: /etc/kubernetes
manifest_config_dir: /etc/kubernetes/manifests
cert_dir: /etc/kubernetes/pki
master_cert_dir: /opt/kubernetes/pki
kube_addon_dir: /etc/kubernetes/addon
flannel_dir: /etc/sysconfig

#- get k8s version
k8s_version: "v1.10.3"

#- image and other variable
api_image: gcr.io/google_containers/kube-apiserver-amd64:v1.10.3
controller_image: gcr.io/google_containers/kube-controller-manager-amd64:v1.10.3
scheduler_image: gcr.io/google_containers/kube-scheduler-amd64:v1.10.3
kube_proxy_image: gcr.io/google_containers/kube-proxy-amd64:v1.10.3

#- cluster service ip range
service_ip_range: 10.96.0.0/24
kubernetes_service_ip: 10.96.0.1  #- IP of default kubernetes service, it is the first IP of network CIDR range

#- all certifactes for cluster  
account_key: /etc/kubernetes/pki/apiserver-key.pem
ca_cert: /etc/kubernetes/pki/ca.pem
ca_key: /etc/kubernetes/pki/ca-key.pem
api_cert: /etc/kubernetes/pki/apiserver.pem
api_key: /etc/kubernetes/pki/apiserver-key.pem
admin_key: /etc/kubernetes/pki/admin-key.pem
admin_cert: /etc/kubernetes/pki/admin.pem
node_cert: /etc/kubernetes/pki/node.pem
node_key: /etc/kubernetes/pki/node-key.pem

#- api secure port and api loadbalancer IP
api_secure_port: 5443
api_lb_ip: https://192.168.50.11 # it should be haproxy host IP or network load balancer IP  # if using onle one api server then setup IP of it
lb_ip: 192.168.50.11

#- kubeconfig file 
kubeletconfig: /etc/kubernetes/kubeletconfig
kubeadminconfig: /etc/kubernetes/kubeadminconfig

# all master fqdn name - it require to create ssl certificate
# set it to only available api server
masters_fqdn: ['master1', 'master2']

#- cluster dns name and IP
cluster_name: cluster.local

#- api authorization ABAC and RBAC
auth_mode: RBAC,ABAC
auth_file: /etc/kubernetes/auth.csv
policy_file: /etc/kubernetes/policy.json

#- admin/readonly user password
admin_user: kube-admin
admin_pass: AdminPass
readonly_user: readonly
readonly_pass: readonly

# kube-proxy addon
kube_proxy: true # set true only if cluster is fully operation and running

#- kube-dns add-on
kube_dns: true # set true only if cluster is fully operation and running
#- if true then set following
dns_ip: 10.96.0.10 # it should be from cluster service_ip_range
dns_replicas: 1

#flannel network # only one network plugin should be enable either weave or flannel
flannel: true
flannel_network: "10.244.0.0/18"
flannel_key: "/atomic.io/network"
flannel_subnet_len: 24
flannel_backend: vxlan

# A list of insecure registrys you might need to define
insecure_registrys:

# Turn to false to disable cluster monitoring with heapster and influxdb
cluster_monitoring: false # set true only if cluster is fully operation and running
#- if true then set following
heapster_ip: 10.96.0.11 # it should be from cluster service_ip_range
heapster_port: 80
grafana_ip: 192.168.50.11 # it should be one of cluster node IP
grafana_port: 100
influx_ip: 192.168.50.11 # it should be one of cluster node IP
influx_port: 8086

# Turn to false to disable the kube-dash addon for this cluster
kube_dash: true  # set true only if cluster is fully operation and running
#- if true then set following
kube_dash_ip: 192.168.50.11 # it should be one of cluster node IP
kube_dash_port: 80

#- setup haproxy for loadbalancing
haproxy: true  # set false when already physical loadbalancer available
haproxy_dir: /etc/haproxy
haproxy_monitor_port: 9090
haadmin_user: admin
haadmin_password: admin123

#- etcd config
domain_name: test.com #- use to create wildcard ssl certificate for api and etcd
etcd_peer_url_scheme: http #- for http  or https
etcd_ca_file: "/etc/kubernetes/pki/ca.pem"
etcd_cert_file: "/etc/kubernetes/pki/etcd.pem"
etcd_key_file: "/etc/kubernetes/pki/etcd-key.pem"
etcd_peer_ca_file: "/etc/kubernetes/pki/ca.pem"
etcd_peer_cert_file: "/etc/kubernetes/pki/etcd.pem"
etcd_peer_key_file: "/etc/kubernetes/pki/etcd-key.pem"

#- proxy configuration of yum repositories
# -> uncomment if running with vagrant
#yum_proxy: "http://192.168.50.99:3128"
yum_proxy: ""

##- use containerd instead of docker
use_containerd: "true"
containerd_release_version: 1.1.0-rc.0
cni_bin_dir: /opt/cni/bin/
cni_conf_dir: /etc/cni/net.d/
cni_version: v0.7.1
